// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.IO;
using Core.Entities;
using Core.Entities.SovTask;
using Microsoft.EntityFrameworkCore;

namespace Infra
{
    public partial class Db : DbContext
    {
        public Db(DbContextOptions<Db> options)
            : base(options)
        {
        }
        public virtual DbSet<ApplicationMenu> ApplicationMenus { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<Joke> Jokes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<People> Peoples { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies(false);
            if (!optionsBuilder.IsConfigured)
            {
                
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AspNetUserRole>()
                .HasKey(r => new
                {
                    r.RoleId,
                    r.UserId
                })
                ;

            modelBuilder.Entity<AspNetUserLogin>()
                .HasKey(l => new
                {
                    l.LoginProvider,
                    l.ProviderKey,
                    l.UserId
                });

            modelBuilder.Entity<AspNetUserToken>()
                .HasKey(l => new
                {
                    l.UserId,
                    l.LoginProvider,
                    l.Name
                });
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}