// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities
{
    public partial class ApplicationMenu : BaseEntity
    {        
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(80)]
        public string MenuTitle { get; set; }
        [Required]
        [StringLength(150)]
        public string MenuName { get; set; }
        [Required]
        [StringLength(128)]
        public string ParentId { get; set; }
        [StringLength(80)]
        public string UrlTitle { get; set; }
        [StringLength(80)]
        public string RouterLink { get; set; }
        [StringLength(80)]
        public string Component { get; set; }
        [StringLength(150)]
        public string RouteData { get; set; }
        public int MenuOrder { get; set; }
        [StringLength(50)]
        public string MenuIcon { get; set; }
        public int? MenuLevel { get; set; }
        public string Target { get; set; }
        public bool ExpandOnly { get; set; }
        public bool? HasSubMenu { get; set; }
        [Required]
        public bool? IsVisible { get; set; }
    }
}